name: Periodic Health Check

on:
  #schedule:
  # - cron:  '*/10 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://fullstack-pokedex-mainul.herokuapp.com/
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s